const POPULAR_CATALOG = [
    { animeId: 16498, animeTitle: "Attack on Titan", animeScore: 8 },
    { animeId: 1535, animeTitle: "Death Note", animeScore: 8 },
    { animeId: 5114, animeTitle: "Fullmetal Alchemist: Brotherhood", animeScore: 9 },
    { animeId: 30276, animeTitle: "One-Punch Man", animeScore: 8 },
    { animeId: 38000, animeTitle: "Demon Slayer: Kimetsu no Yaiba", animeScore: 8 },
    { animeId: 11757, animeTitle: "Sword Art Online", animeScore: 7 },
    { animeId: 31964, animeTitle: "My Hero Academia", animeScore: 7 },
    { animeId: 11061, animeTitle: "Hunter x Hunter", animeScore: 9 },
    { animeId: 20, animeTitle: "Naruto", animeScore: 8 },
    { animeId: 22319, animeTitle: "Tokyo Ghoul", animeScore: 7 },
    { animeId: 32281, animeTitle: "Your Name.", animeScore: 8 },
    { animeId: 25777, animeTitle: "Attack on Titan Season 2", animeScore: 8 },
    { animeId: 40748, animeTitle: "Jujutsu Kaisen", animeScore: 8 },
    { animeId: 9253, animeTitle: "Steins;Gate", animeScore: 9 },
    { animeId: 1735, animeTitle: "Naruto Shippuden", animeScore: 8 },
    { animeId: 33486, animeTitle: "My Hero Academia Season 2", animeScore: 8 },
    { animeId: 21, animeTitle: "One Piece", animeScore: 8 },
    { animeId: 35760, animeTitle: "Attack on Titan Season 3", animeScore: 8 },
    { animeId: 28851, animeTitle: "A Silent Voice", animeScore: 8 },
    { animeId: 38524, animeTitle: "Attack on Titan Season 3 Part 2", animeScore: 9 },
    { animeId: 19815, animeTitle: "No Game, No Life", animeScore: 8 },
    { animeId: 1575, animeTitle: "Code Geass: Lelouch of the Rebellion", animeScore: 8 },
    { animeId: 31240, animeTitle: "Re:ZERO -Starting Life in Another World-", animeScore: 8 },
    { animeId: 23273, animeTitle: "Your Lie in April", animeScore: 8 },
    { animeId: 36456, animeTitle: "My Hero Academia Season 3", animeScore: 7 },
    { animeId: 4224, animeTitle: "Toradora!", animeScore: 8 },
    { animeId: 20507, animeTitle: "Noragami", animeScore: 7 },
    { animeId: 32182, animeTitle: "Mob Psycho 100", animeScore: 8 },
    { animeId: 31043, animeTitle: "Erased", animeScore: 8 },
    { animeId: 40028, animeTitle: "Attack on Titan: Final Season", animeScore: 8 },
    { animeId: 22199, animeTitle: "Akame ga Kill!", animeScore: 7 },
    { animeId: 23755, animeTitle: "The Seven Deadly Sins", animeScore: 7 },
    { animeId: 24833, animeTitle: "Assassination Classroom", animeScore: 8 },
    { animeId: 6547, animeTitle: "Angel Beats!", animeScore: 8 },
    { animeId: 269, animeTitle: "Bleach", animeScore: 7 },
    { animeId: 20583, animeTitle: "Haikyu!!", animeScore: 8 },
    { animeId: 37779, animeTitle: "The Promised Neverland", animeScore: 8 },
    { animeId: 30831, animeTitle: "KonoSuba: God's Blessing on This Wonderful World!", animeScore: 8 },
    { animeId: 10620, animeTitle: "The Future Diary", animeScore: 7 },
    { animeId: 21881, animeTitle: "Sword Art Online II", animeScore: 6 },
    { animeId: 9919, animeTitle: "Blue Exorcist", animeScore: 7 },
    { animeId: 1, animeTitle: "Cowboy Bebop", animeScore: 8 },
    { animeId: 22535, animeTitle: "Parasyte: The Maxim", animeScore: 8 },
    { animeId: 199, animeTitle: "Spirited Away", animeScore: 8 },
    { animeId: 30, animeTitle: "Neon Genesis Evangelion", animeScore: 8 },
    { animeId: 33352, animeTitle: "Violet Evergarden", animeScore: 8 },
    { animeId: 37450, animeTitle: "Rascal Does Not Dream of Bunny Girl Senpai", animeScore: 8 },
    { animeId: 2904, animeTitle: "Code Geass: Lelouch of the Rebellion R2", animeScore: 8 },
    { animeId: 38691, animeTitle: "Dr. Stone", animeScore: 8 },
    { animeId: 44511, animeTitle: "Chainsaw Man", animeScore: 8 },
    { animeId: 37999, animeTitle: "Kaguya-sama: Love is War", animeScore: 8 },
    { animeId: 28223, animeTitle: "Death Parade", animeScore: 8 },
    { animeId: 38408, animeTitle: "My Hero Academia Season 4", animeScore: 7 },
    { animeId: 27899, animeTitle: "Tokyo Ghoul A", animeScore: 7 },
    { animeId: 34572, animeTitle: "Black Clover", animeScore: 8 },
    { animeId: 34134, animeTitle: "One-Punch Man Season 2", animeScore: 7 },
    { animeId: 50265, animeTitle: "Spy x Family", animeScore: 8 },
    { animeId: 18679, animeTitle: "Kill la Kill", animeScore: 8 },
    { animeId: 6702, animeTitle: "Fairy Tail", animeScore: 7 },
    { animeId: 14719, animeTitle: "JoJo's Bizarre Adventure (2012)", animeScore: 7 },
    { animeId: 35849, animeTitle: "DARLING in the FRANXX", animeScore: 7 },
    { animeId: 37521, animeTitle: "Vinland Saga", animeScore: 8 },
    { animeId: 11111, animeTitle: "Another", animeScore: 7 },
    { animeId: 40456, animeTitle: "Demon Slayer: Kimetsu no Yaiba - The Movie: Mugen Train", animeScore: 8 },
    { animeId: 3588, animeTitle: "Soul Eater", animeScore: 7 },
    { animeId: 2001, animeTitle: "Gurren Lagann", animeScore: 8 },
    { animeId: 35790, animeTitle: "The Rising of the Shield Hero", animeScore: 7 },
    { animeId: 28999, animeTitle: "Charlotte", animeScore: 7 },
    { animeId: 29803, animeTitle: "Overlord", animeScore: 7 },
    { animeId: 28171, animeTitle: "Food Wars! Shokugeki no Soma", animeScore: 8 },
    { animeId: 13601, animeTitle: "Psycho-Pass", animeScore: 8 },
    { animeId: 47778, animeTitle: "Demon Slayer: Kimetsu no Yaiba Entertainment District Arc", animeScore: 8 },
    { animeId: 37510, animeTitle: "Mob Psycho 100 II", animeScore: 8 },
    { animeId: 9989, animeTitle: "Anohana: The Flower We Saw That Day", animeScore: 8 },
    { animeId: 15809, animeTitle: "The Devil is a Part-Timer!", animeScore: 7 },
    { animeId: 28121, animeTitle: "Is It Wrong to Try to Pick Up Girls in a Dungeon?", animeScore: 7 },
    { animeId: 32937, animeTitle: "KonoSuba: God's Blessing on This Wonderful World! 2", animeScore: 8 },
    { animeId: 37430, animeTitle: "That Time I Got Reincarnated as a Slime", animeScore: 8 },
    { animeId: 34933, animeTitle: "Kakegurui", animeScore: 7 },
    { animeId: 42897, animeTitle: "Horimiya", animeScore: 8 },
    { animeId: 226, animeTitle: "Elfen Lied", animeScore: 7 },
    { animeId: 8074, animeTitle: "High School of the Dead", animeScore: 7 },
    { animeId: 10087, animeTitle: "Fate/Zero", animeScore: 8 },
    { animeId: 30654, animeTitle: "Assassination Classroom Second Season", animeScore: 8 },
    { animeId: 28891, animeTitle: "Haikyu!! 2nd Season", animeScore: 8 },
    { animeId: 14813, animeTitle: "My Teen Romantic Comedy SNAFU", animeScore: 8 },
    { animeId: 121, animeTitle: "Fullmetal Alchemist", animeScore: 8 },
    { animeId: 39535, animeTitle: "Mushoku Tensei: Jobless Reincarnation", animeScore: 8 },
    { animeId: 51179, animeTitle: "Mushoku Tensei: Jobless Reincarnation Season 2", animeScore: 8 },
    { animeId: 55888, animeTitle: "Mushoku Tensei: Jobless Reincarnation Season 2 Part 2", animeScore: 8 },
    { animeId: 30503, animeTitle: "Noragami Aragoto", animeScore: 8 },
    { animeId: 31478, animeTitle: "Bungo Stray Dogs", animeScore: 7 },
    { animeId: 34599, animeTitle: "Made in Abyss", animeScore: 8 },
    { animeId: 48583, animeTitle: "Attack on Titan: Final Season Part 2", animeScore: 8 },
    { animeId: 11617, animeTitle: "High School DxD", animeScore: 7 },
    { animeId: 38671, animeTitle: "Fire Force", animeScore: 7 },
    { animeId: 2167, animeTitle: "Clannad", animeScore: 7 },
    { animeId: 40591, animeTitle: "Kaguya-sama: Love is War?", animeScore: 8 },
    { animeId: 6746, animeTitle: "Durarara!!", animeScore: 8 },
    { animeId: 5081, animeTitle: "Bakemonogatari", animeScore: 8 },
    { animeId: 431, animeTitle: "Howl's Moving Castle", animeScore: 8 },
    { animeId: 12189, animeTitle: "Hyouka", animeScore: 8 },
    { animeId: 14741, animeTitle: "Love, Chunibyo & Other Delusions!", animeScore: 7 },
    { animeId: 35507, animeTitle: "Classroom of the Elite", animeScore: 7 },
    { animeId: 9756, animeTitle: "Puella Magi Madoka Magica", animeScore: 8 },
    { animeId: 42249, animeTitle: "Tokyo Revengers", animeScore: 7 },
    { animeId: 164, animeTitle: "Princess Mononoke", animeScore: 8 },
    { animeId: 37520, animeTitle: "Dororo", animeScore: 8 },
    { animeId: 20899, animeTitle: "JoJo's Bizarre Adventure: Stardust Crusaders", animeScore: 8 },
    { animeId: 52991, animeTitle: "Frieren: Beyond Journey's End", animeScore: 9 },
    { animeId: 51009, animeTitle: "Jujutsu Kaisen Season 2", animeScore: 8 },
    { animeId: 41587, animeTitle: "My Hero Academia Season 5", animeScore: 7 },
    { animeId: 205, animeTitle: "Samurai Champloo", animeScore: 8 },
    { animeId: 7054, animeTitle: "Maid Sama!", animeScore: 7 },
    { animeId: 33206, animeTitle: "Miss Kobayashi's Dragon Maid", animeScore: 7 },
    { animeId: 13759, animeTitle: "The Pet Girl of Sakurasou", animeScore: 8 },
    { animeId: 813, animeTitle: "Dragon Ball Z", animeScore: 8 },
    { animeId: 32935, animeTitle: "Haikyu!! 3rd Season", animeScore: 8 },
    { animeId: 6880, animeTitle: "Deadman Wonderland", animeScore: 7 },
    { animeId: 19, animeTitle: "Monster", animeScore: 8 },
    { animeId: 11771, animeTitle: "Kuroko's Basketball", animeScore: 8 },
    { animeId: 48736, animeTitle: "My Dress-Up Darling", animeScore: 8 },
    { animeId: 36511, animeTitle: "Tokyo Ghoul:re", animeScore: 6 },
    { animeId: 4181, animeTitle: "Clannad: After Story", animeScore: 8 },
    { animeId: 10793, animeTitle: "Guilty Crown", animeScore: 7 },
    { animeId: 23283, animeTitle: "Terror in Resonance", animeScore: 8 },
    { animeId: 4898, animeTitle: "Black Butler", animeScore: 7 },
    { animeId: 35120, animeTitle: "Devilman: Crybaby", animeScore: 7 },
    { animeId: 39587, animeTitle: "Re:ZERO -Starting Life in Another World- Season 2", animeScore: 8 },
    { animeId: 31933, animeTitle: "JoJo's Bizarre Adventure: Diamond Is Unbreakable", animeScore: 8 },
    { animeId: 33255, animeTitle: "The Disastrous Life of Saiki K.", animeScore: 8 },
    { animeId: 18153, animeTitle: "Beyond the Boundary", animeScore: 7 },
    { animeId: 26055, animeTitle: "JoJo's Bizarre Adventure: Stardust Crusaders - Battle in Egypt", animeScore: 8 },
    { animeId: 48561, animeTitle: "Jujutsu Kaisen 0", animeScore: 8 },
    { animeId: 37349, animeTitle: "Goblin Slayer", animeScore: 7 },
    { animeId: 853, animeTitle: "Ouran High School Host Club", animeScore: 8 },
    { animeId: 34577, animeTitle: "The Seven Deadly Sins: Revival of the Commandments", animeScore: 7 },
    { animeId: 40852, animeTitle: "Dr. Stone: Stone Wars", animeScore: 8 },
    { animeId: 11741, animeTitle: "Fate/Zero Season 2", animeScore: 8 },
    { animeId: 17265, animeTitle: "Log Horizon", animeScore: 7 },
    { animeId: 22297, animeTitle: "Fate/stay night [Unlimited Blade Works]", animeScore: 8 },
    { animeId: 14227, animeTitle: "My Little Monster", animeScore: 7 },
    { animeId: 523, animeTitle: "My Neighbor Totoro", animeScore: 8 },
    { animeId: 23847, animeTitle: "My Teen Romantic Comedy SNAFU TOO!", animeScore: 8 },
    { animeId: 37991, animeTitle: "JoJo's Bizarre Adventure: Golden Wind", animeScore: 8 },
    { animeId: 918, animeTitle: "Gintama", animeScore: 8 },
    { animeId: 36474, animeTitle: "Sword Art Online: Alicization", animeScore: 7 },
    { animeId: 223, animeTitle: "Dragon Ball", animeScore: 7 },
    { animeId: 30015, animeTitle: "ReLIFE", animeScore: 8 },
    { animeId: 17895, animeTitle: "Golden Time", animeScore: 8 },
    { animeId: 35073, animeTitle: "Overlord II", animeScore: 8 },
    { animeId: 5680, animeTitle: "K-ON!", animeScore: 8 },
    { animeId: 38826, animeTitle: "Weathering with You", animeScore: 8 },
    { animeId: 50602, animeTitle: "Spy x Family Part 2", animeScore: 8 },
    { animeId: 14513, animeTitle: "Magi: The Labyrinth of Magic", animeScore: 8 },
    { animeId: 15583, animeTitle: "Date A Live", animeScore: 7 },
    { animeId: 52299, animeTitle: "Solo Leveling", animeScore: 8 },
    { animeId: 45576, animeTitle: "Mushoku Tensei: Jobless Reincarnation Part 2", animeScore: 9 },
    { animeId: 36098, animeTitle: "I Want To Eat Your Pancreas", animeScore: 9 },
    { animeId: 889, animeTitle: "Black Lagoon", animeScore: 8 },
    { animeId: 39551, animeTitle: "That Time I Got Reincarnated as a Slime Season 2", animeScore: 8 },
    { animeId: 43608, animeTitle: "Kaguya-sama: Love is War -Ultra Romantic-", animeScore: 9 },
    { animeId: 30240, animeTitle: "Prison School", animeScore: 8 },
    { animeId: 51019, animeTitle: "Demon Slayer: Kimetsu no Yaiba Swordsmith Village Arc", animeScore: 8 },
    { animeId: 35968, animeTitle: "Wotakoi: Love is Hard for Otaku", animeScore: 8 },
    { animeId: 40839, animeTitle: "Rent-a-Girlfriend", animeScore: 7 },
    { animeId: 6045, animeTitle: "Kimi ni Todoke: From Me to You", animeScore: 8 },
    { animeId: 40221, animeTitle: "Tower of God", animeScore: 8 },
    { animeId: 38101, animeTitle: "The Quintessential Quintuplets", animeScore: 8 },
    { animeId: 42203, animeTitle: "Re:ZERO -Starting Life in Another World- Season 2 Part 2", animeScore: 8 },
    { animeId: 38883, animeTitle: "Haikyu!! To the Top", animeScore: 8 },
    { animeId: 35788, animeTitle: "Food Wars! The Third Plate", animeScore: 8 },
    { animeId: 32615, animeTitle: "Saga of Tanya the Evil", animeScore: 8 },
    { animeId: 32, animeTitle: "Neon Genesis Evangelion: The End of Evangelion", animeScore: 9 },
    { animeId: 52034, animeTitle: "[Oshi No Ko]", animeScore: 9 },
    { animeId: 42310, animeTitle: "Cyberpunk: Edgerunners", animeScore: 9 },
    { animeId: 27775, animeTitle: "Plastic Memories", animeScore: 8 },
    { animeId: 777, animeTitle: "Hellsing Ultimate", animeScore: 8 },
    { animeId: 1689, animeTitle: "5 Centimeters per Second", animeScore: 8 },
    { animeId: 21995, animeTitle: "Blue Spring Ride", animeScore: 8 },
    { animeId: 2025, animeTitle: "Darker than Black", animeScore: 8 },
    { animeId: 48926, animeTitle: "Komi Can't Communicate", animeScore: 8 },
    { animeId: 16592, animeTitle: "Danganronpa: The Animation", animeScore: 7 },
    { animeId: 356, animeTitle: "Fate/stay night", animeScore: 7 },
    { animeId: 41353, animeTitle: "The God of High School", animeScore: 7 },
    { animeId: 39617, animeTitle: "The Promised Neverland Season 2", animeScore: 5 },
    { animeId: 41025, animeTitle: "To Your Eternity", animeScore: 8 },
    { animeId: 20787, animeTitle: "Black Bullet", animeScore: 7 },
    { animeId: 15451, animeTitle: "High School DxD New", animeScore: 7 },
    { animeId: 49926, animeTitle: "Demon Slayer: Kimetsu no Yaiba Mugen Train Arc", animeScore: 8 },
    { animeId: 36649, animeTitle: "Banana Fish", animeScore: 8 },
    { animeId: 2251, animeTitle: "Baccano!", animeScore: 8 },
    { animeId: 41457, animeTitle: "86 Eighty-Six", animeScore: 8 },
    { animeId: 39195, animeTitle: "Beastars", animeScore: 8 },
    { animeId: 32995, animeTitle: "Yuri!!! On Ice", animeScore: 8 },
    { animeId: 30484, animeTitle: "Steins;Gate 0", animeScore: 9 },
    { animeId: 47, animeTitle: "Akira", animeScore: 8 },
    { animeId: 32867, animeTitle: "Bungo Stray Dogs 2", animeScore: 8 },
    { animeId: 33674, animeTitle: "No Game, No Life: Zero", animeScore: 8 },
    { animeId: 38680, animeTitle: "Fruits Basket 1st Season", animeScore: 8 },
    { animeId: 57334, animeTitle: "Dan Da Dan", animeScore: 8 },
    { animeId: 34566, animeTitle: "Boruto: Naruto Next Generations", animeScore: 6 },
    { animeId: 16894, animeTitle: "Kuroko's Basketball 2", animeScore: 8 },
    { animeId: 46569, animeTitle: "Hell's Paradise", animeScore: 8 },
    { animeId: 40776, animeTitle: "Haikyu!! To the Top 2nd-cour", animeScore: 9 },
    { animeId: 245, animeTitle: "Great Teacher Onizuka", animeScore: 9 },
    { animeId: 30694, animeTitle: "Dragon Ball Super", animeScore: 7 },
    { animeId: 14345, animeTitle: "BTOOOM!", animeScore: 7 },
    { animeId: 457, animeTitle: "Mushi-Shi", animeScore: 9 },
    { animeId: 25157, animeTitle: "Trinity Seven", animeScore: 7 },
    { animeId: 41487, animeTitle: "That Time I Got Reincarnated as a Slime Season 2 Part 2", animeScore: 8 },
    { animeId: 40496, animeTitle: "The Misfit of Demon King Academy", animeScore: 7 },
    { animeId: 37105, animeTitle: "Grand Blue Dreaming", animeScore: 8 },
    { animeId: 18115, animeTitle: "Magi: The Kingdom of Magic", animeScore: 8 },
    { animeId: 32729, animeTitle: "Orange", animeScore: 8 },
    { animeId: 227, animeTitle: "FLCL", animeScore: 8 },
    { animeId: 339, animeTitle: "Serial Experiments Lain", animeScore: 8 },
    { animeId: 11887, animeTitle: "Kokoro Connect", animeScore: 8 },
    { animeId: 11843, animeTitle: "Daily Lives of High School Boys", animeScore: 8 },
    { animeId: 49596, animeTitle: "Blue Lock", animeScore: 8 },
    { animeId: 38040, animeTitle: "KonoSuba: God's Blessing on This Wonderful World! - Legend of Crimson", animeScore: 8 },
    { animeId: 2966, animeTitle: "Spice and Wolf", animeScore: 8 },
    { animeId: 12355, animeTitle: "Wolf Children", animeScore: 9 },
    { animeId: 40356, animeTitle: "The Rising of the Shield Hero Season 2", animeScore: 7 },
    { animeId: 249, animeTitle: "InuYasha", animeScore: 8 },
];

module.exports = {
    POPULAR_CATALOG
};
