const SOURCE_MODES = ['POPULAR', 'MAL_ONLY', 'HYBRID'];
const SELECTION_MODES = ['STANDARD', 'BALANCED_STRICT', 'BALANCED_RELAXED'];
const THEME_MODES = ['OP_ONLY', 'ED_ONLY', 'MIXED'];

const MAX_LOBBY_SIZE = 8;
const MIN_LOBBY_SIZE = 1;

module.exports = {
    SOURCE_MODES,
    SELECTION_MODES,
    THEME_MODES,
    MAX_LOBBY_SIZE,
    MIN_LOBBY_SIZE
};
